apiVersion: v2
appVersion: 2.3.1
dependencies:
- name: metaflow-service
  repository: ""
  version: 0.2.0
  condition: metaflow-service.enabled
- name: metaflow-ui
  repository: ""
  version: 0.2.0
  condition: metaflow-ui.enabled
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: ~12.2.2
  condition: postgresql.enabled
- name: minio
  version: ~12.6.4
  repository: "https://charts.bitnami.com/bitnami"
  condition: minio.enabled
- name: traefik
  version: ~25.0.0
  repository: "https://traefik.github.io/charts"
  condition: traefik.enabled
description: Machine Learning plaform
home: https://metaflow.org
keywords:
- mlops
name: metaflow
sources:
- https://github.com/Netflix/metaflow
- https://github.com/outerbounds/metaflow-tools
type: application
version: 0.0.1
