apiVersion: v1
kind: Pod
metadata:
  labels:
    run: py-shell
  name: py-shell
spec:
  containers:
  - args:
    - bash
    env:
    - name: USERNAME
      value: anonymous
    image: python:3
    name: py-shell
    stdin: true
    stdinOnce: true
    tty: true
